# Generated by Django 4.2 on 2025-07-20 14:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('emprestimo', '0002_pagamento'),
    ]

    operations = [
        migrations.AlterField(
            model_name='emprestimo',
            name='data_solicitacao',
            field=models.DateField(auto_now_add=True),
        ),
    ]
